server {
    listen 80;
    access_log /data/logs/nginx_access.log;
    error_log /data/logs/nginx_error.log notice;

    location / {
        root /opt/dist/;
        try_files $uri $uri/ /index.html;
        add_header Cache-Control no-cache;
    }

    location = /index.html {
        root /opt/dist/;
        expires -1;
    }
}
